server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/train_ticket}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    validate-on-migrate: false
    table: flyway_trains_history
    baseline-on-migrate: true
    baseline-version: 0
